site_name: KlongPy
site_url: https://briangu.github.io/klongpy
repo_url: https://github.com/briangu/klongpy
repo_name: briangu/klongpy

# Define the source directory for Markdown files
docs_dir: 'docs'

# Define the directory for the built HTML files
site_dir: 'site'

# Navigation structure
nav:
  - Home: 'index.md'
  - Quick Start: 'quick-start.md'
  - Examples: 'examples.md'
  - Guides:
      - Python Integration: 'python_integration.md'
      - PyTorch Backend & Autograd: 'torch_backend.md'
      - Performance: 'performance.md'
  - Reference:
      - Operators: 'operators.md'
      - REPL: 'repl.md'
  - Data & Systems:
      - Fast Columnar Database: 'fast_columnar_database.md'
      - Table & Key-Value Store: 'table_and_key_value_stores.md'
      - IPC Capabilities: 'ipc_capabilities.md'
      - Web Server: 'web_server.md'
      - WebSockets: 'websockets.md'
      - Timers: 'timer.md'

# Theme configuration
theme:
  name: 'material'
  logo: 'assets/images/klongpy_logo.jpg'
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Plugins configuration (if any plugins are used)
plugins:
  - search

# Extensions configuration (if any Markdown extensions are used)
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Google Analytics or other tracking (if you want to add tracking)
# google_analytics:
#   - 'UA-XXXXX-X'
#   - 'auto'
